notify = ["python3", "/Users/malthejorgensen/.codex/notifier.py"]
model = "gpt-5.2-codex"

# See:
# - https://developers.openai.com/codex/config-basic/
# - https://developers.openai.com/codex/security
# - https://github.com/openai/codex/blob/main/docs/config.md

# The two options below are equivalent to executing as `codex --full-auto`
#
# Default to writeable sandbox
sandbox_mode = "workspace-write"
# Sane approval policy
approval_policy = "on-request" # Other options: "untrusted", "never"
# Allow the model to request web searches
web_search = "cached"

[features]
shell_snapshot = true           # Speed up repeated commands
undo = false                    # No git ghost commits

[sandbox_workspace_write]
# Fixes `uv` when running in sandbox (system-configuration / dynamic_store.rs)
# See: https://github.com/openai/codex/issues/5914#issuecomment-3505687500
network_access = true

[tui]
animations = false          # Don't animate text in the TUI (makes it possible to copy/paste login URL)
